import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../assets/styles/globals.css'
import '../assets/styles/scrollbar.css'
import { Header } from '@/components/header'
import ClientProviders from '@/utils/client-providers'
import { StepMarker } from '@/components/step-marker'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="tp-br">
      <body className={inter.className}>
        <Header />
        <StepMarker />

        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  )
}
