import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '../assets/styles/globals.css'
import '../assets/styles/scrollbar.css'
import { Header } from '@/components/header'
import ClientProviders from '@/utils/client-providers'
import { StepMarker } from '@/components/step-marker'
import { BgDecorator } from '@/components/bg-decorator'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="tp-br">
      <body className={roboto.variable}>
        <Header />
        <StepMarker />
        <BgDecorator />

        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  )
}
